name: release

on:
  push:
    branches: [main]

permissions: {}

concurrency:
  group: release-main
  cancel-in-progress: false
  queue: max

jobs:
  release:
    uses: vipentti/npm-release-flow/.github/workflows/release.yml@52ed8464f60e1befbffe5fdfe473e32e5138cdaa
    permissions:
      contents: write
      pull-requests: read
      id-token: write
    secrets:
      NPM_RELEASE_FLOW_GPG_PRIVATE_KEY: ${{ secrets.NPM_RELEASE_FLOW_GPG_PRIVATE_KEY }}
      NPM_RELEASE_FLOW_GPG_PASSPHRASE: ${{ secrets.NPM_RELEASE_FLOW_GPG_PASSPHRASE }}
      NPM_RELEASE_FLOW_GPG_PUBLIC_KEY: ${{ secrets.NPM_RELEASE_FLOW_GPG_PUBLIC_KEY }}
      NPM_RELEASE_FLOW_APP_PRIVATE_KEY: ${{ secrets.NPM_RELEASE_FLOW_APP_PRIVATE_KEY }}
